### ISSUE TITLE
SVG grammar broken

### ISSUE THREAD

**Issue by wooorm** [Alhadis/language-etc#11]
Not sure what this line is supposed to do:

https://github.com/Alhadis/language-etc/blob/b5bd781b25e5639c3a380c976c6d16b5ccd04ef9/grammars/svg.cson#L46

But that pattern shouldn’t ever match? 🤔 Lookahead for `A`, which is actually `B`?

I don’t really get why this other stuff is in the root `patterns` anyway? Why not just include `#main`? Why are extra drawing commands in there?

**Comment by Alhadis** [comment]
What exactly appears to be the highlighting issue?

**Comment by wooorm** [comment]
The pattern never ends because the end match never matches, which is a problem when embedding this language in other languages, and SVG never ends

**Comment by Alhadis** [comment]
Can you show me a _specific example_?

**Comment by wooorm** [comment]
I don’t understand what you are asking? Example of what? I feel like my first comment links to the specific example of a regex that never matches?

Are you wondering how I am using the SVG grammar as an embedded language? If so, then here is a specific example:

```js
{
  begin:
    '(?:^|\\G)(?:[ ]{0,3})(`{3,})[\\t ]*(?:(\\g<info>)(?:[\\t ]+\\g<meta>)?[\\t ]*)?$(?<info>(?i:\\.?(?:svg))){0}(?<meta>[^\\n\\r`]+){0}',
  beginCaptures: {
    1: {
      name: 'punctuation.definition.string.begin.code.fenced.md'
    },
    2: {
      name: 'entity.name.function.md'
    }
  },
  contentName: 'meta.embedded.svg',
  end: '(?:^|\\G)[ ]{0,3}(\\1)[\\t ]*$',
  endCaptures: {
    1: {
      name: 'punctuation.definition.string.end.code.fenced.md'
    }
  },
  name: 'markup.code.svg.md',
  patterns: [
    {
      include: 'text.xml.svg'
    }
  ]
}
```

**Comment by Alhadis** [comment]
I'm asking you to cite a particular **existing** example of where this is causing problems.

The impossible match (`(?=A)B`) is intentional.

**Comment by wooorm** [comment]
> *existing* example

Huh, what is “existing”? Existing where? What do you deem “existing”?

So, it is intentional that this project is shipping a grammar that can’t be embedded, and thus cannot be used with other grammars?

**Comment by Alhadis** [comment]
Sorry for the confusion, I took a look at the grammar's source once I had access to a desktop machine, and realised that an unconditional redirect was kind of pointless.

("Redirect" is what I call a TextMate grammar rule that slurps the rest of the document with an impossible pattern (conventionally `(?=A)B`), and is only meant to be used in controlled circumstances; e.g., an `__END__` marker in a Perl or Ruby program.)
