### ISSUE TITLE
Issue with syntax highlighting SVG

### ISSUE THREAD

**Issue by printfn** [Alhadis/language-etc#13]
It looks like the SVG grammar in this repository is used on GitHub, right? I noticed that this SVG file isn’t being syntax-highlighted correctly:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="500" height="500">
    <defs>
        <linearGradient id="backgroundGradient" x1="0%" y1="0%" x2="0%" y2="100%">
            <stop offset="0%" style="stop-color:#ffbc6b;stop-opacity:1" />
            <stop offset="100%" style="stop-color:#ff8100;stop-opacity:1" />
        </linearGradient>
    </defs>
</svg>
```

Original file: https://github.com/printfn/fend/blob/567bb4c8bf0cf2aeb459c2c7cd463294f2faf007/icon/icon.svg

**Comment by Alhadis** [comment]
@printfn Just a heads-up that GitHub [fixed](https://github.com/github-linguist/linguist/issues/6668#issuecomment-1992223278) the aforementioned issue this morning. Your SVG code should now be correctly-highlighted again. 😉
